"""create_factura_archivos_cliente_table

Revision ID: 43c85ff3fc45
Revises: bb19c5a7e210
Create Date: 2026-04-20 23:49:08.160805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c85ff3fc45'
down_revision: Union[str, Sequence[str], None] = 'bb19c5a7e210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_archivos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_archivos_cliente_id'), 'factura_archivos_cliente', ['id'], unique=False)
    op.alter_column('avansat_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avansat_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_factura_archivos_cliente_id'), table_name='factura_archivos_cliente')
    op.drop_table('factura_archivos_cliente')
    # ### end Alembic commands ###
