"""baseline_initial_schema

Revision ID: cb60ea0c7a79
Revises: 
Create Date: 2026-03-18 10:43:13.165199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb60ea0c7a79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_index(op.f('ix_terceros_id'), 'terceros', ['id'], unique=False)
    op.create_table('tipos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_vehiculo_id'), 'tipos_vehiculo', ['id'], unique=False)
    op.create_table('operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('porcentaje_rentabilidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operaciones_id'), 'operaciones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('COINTRA', 'CLIENTE', 'TERCERO', name='userrole'), nullable=False),
    sa.Column('sub_rol', sa.Enum('COINTRA_ADMIN', 'COINTRA_USER', name='cointrasubrol'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('conciliaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'EN_REVISION', 'APROBADA', 'CERRADA', name='conciliacionestado'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('enviada_facturacion', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['operacion_id'], ['operaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conciliaciones_id'), 'conciliaciones', ['id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_codigo'), 'servicios', ['codigo'], unique=True)
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    op.create_index(op.f('ix_servicios_nombre'), 'servicios', ['nombre'], unique=True)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('propietario', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_index(op.f('ix_vehiculos_tercero_id'), 'vehiculos', ['tercero_id'], unique=False)
    op.create_table('catalogo_tarifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tarifa_cliente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rentabilidad_pct', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tarifa_tercero', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('servicio_id', 'tipo_vehiculo_id', name='uq_catalogo_tarifa_servicio_tipo')
    )
    op.create_index(op.f('ix_catalogo_tarifas_id'), 'catalogo_tarifas', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_tarifas_servicio_id'), 'catalogo_tarifas', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_catalogo_tarifas_tipo_vehiculo_id'), 'catalogo_tarifas', ['tipo_vehiculo_id'], unique=False)
    op.create_table('conciliacion_manifiestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=False),
    sa.Column('manifiesto_numero', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifiesto_numero')
    )
    op.create_index(op.f('ix_conciliacion_manifiestos_conciliacion_id'), 'conciliacion_manifiestos', ['conciliacion_id'], unique=False)
    op.create_index(op.f('ix_conciliacion_manifiestos_id'), 'conciliacion_manifiestos', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('email_intentado', sa.Boolean(), nullable=False),
    sa.Column('email_enviado', sa.Boolean(), nullable=False),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_id', sa.Integer(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('conciliacion_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fecha_servicio', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('horas_cantidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conductor', sa.String(length=255), nullable=True),
    sa.Column('tarifa_tercero', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tarifa_cliente', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rentabilidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manifiesto_numero', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cargado_por', sa.String(length=20), nullable=False),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('estado_conciliacion', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['operacion_id'], ['operaciones.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viajes_id'), 'viajes', ['id'], unique=False)
    op.create_table('conciliacion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=False),
    sa.Column('viaje_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('VIAJE', 'PEAJE', 'HORA_EXTRA', 'VIAJE_ADICIONAL', 'ESTIBADA', 'CONDUCTOR_RELEVO', 'OTRO', name='itemtipo'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_REVISION', 'APROBADO', 'RECHAZADO', name='itemestado'), nullable=False),
    sa.Column('fecha_servicio', sa.Date(), nullable=False),
    sa.Column('origen', sa.String(length=255), nullable=True),
    sa.Column('destino', sa.String(length=255), nullable=True),
    sa.Column('placa', sa.String(length=50), nullable=True),
    sa.Column('conductor', sa.String(length=255), nullable=True),
    sa.Column('tarifa_tercero', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tarifa_cliente', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rentabilidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manifiesto_numero', sa.String(length=100), nullable=True),
    sa.Column('remesa', sa.String(length=100), nullable=True),
    sa.Column('cargado_por', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viaje_id'], ['viajes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conciliacion_items_id'), 'conciliacion_items', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['conciliacion_items.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.create_table('historial_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conciliacion_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['conciliacion_items.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_cambios_id'), 'historial_cambios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_cambios_id'), table_name='historial_cambios')
    op.drop_table('historial_cambios')
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_conciliacion_items_id'), table_name='conciliacion_items')
    op.drop_table('conciliacion_items')
    op.drop_index(op.f('ix_viajes_id'), table_name='viajes')
    op.drop_table('viajes')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_conciliacion_manifiestos_id'), table_name='conciliacion_manifiestos')
    op.drop_index(op.f('ix_conciliacion_manifiestos_conciliacion_id'), table_name='conciliacion_manifiestos')
    op.drop_table('conciliacion_manifiestos')
    op.drop_index(op.f('ix_catalogo_tarifas_tipo_vehiculo_id'), table_name='catalogo_tarifas')
    op.drop_index(op.f('ix_catalogo_tarifas_servicio_id'), table_name='catalogo_tarifas')
    op.drop_index(op.f('ix_catalogo_tarifas_id'), table_name='catalogo_tarifas')
    op.drop_table('catalogo_tarifas')
    op.drop_index(op.f('ix_vehiculos_tercero_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_servicios_nombre'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_codigo'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_conciliaciones_id'), table_name='conciliaciones')
    op.drop_table('conciliaciones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_operaciones_id'), table_name='operaciones')
    op.drop_table('operaciones')
    op.drop_index(op.f('ix_tipos_vehiculo_id'), table_name='tipos_vehiculo')
    op.drop_table('tipos_vehiculo')
    op.drop_index(op.f('ix_terceros_id'), table_name='terceros')
    op.drop_table('terceros')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
